namespace MaterialSwitcher
{
    public enum lilToonPropertyType
    {
        RenderingMode,

        // Base Settings
        Cutoff,
        Cull,
        Invisible,
        ZWrite,
        AntiAliasStrength,
        UseDither,
        DitherTex,
        DitherMaxValue,

        // Lighting Base Settings
        LightMinLimit,
        LightMaxLimit,
        MonochromeLighting,
        ShadowEnvStrength,

        // Main Color
        MainColor,
        MainTex,
        MainTexHSVG,
        MainGradationStrength,
        MainGradationTex,
        MainColorAdjustMask,

        // Alpha Mask
        AlphaMaskMode,
        AlphaMask,
        AlphaMaskScale,
        AlphaMaskValue,

        // Shadow
        UseShadow,
        ShadowMaskType,
        ShadowStrength,
        ShadowStrengthMask,
        ShadowStrengthMaskLOD,
        ShadowFlatBorder,
        ShadowFlatBlur,
        ShadowColorType,
        ShadowColor,
        ShadowColorTex,
        ShadowBorder,
        ShadowBlur,
        ShadowReceive,
        Shadow2ndColor,
        Shadow2ndColorTex,
        Shadow2ndBorder,
        Shadow2ndBlur,
        Shadow2ndReceive,
        Shadow3rdColor,
        Shadow3rdColorTex,
        ShadowBorderColor,
        ShadowBorderRange,
        ShadowMainStrength,

        // Emission
        UseEmission,
        EmissionColor,
        EmissionTex,
        EmissionTexScrollRotate,
        EmissionTexUVMode,
        EmissionMainStrength,
        EmissionBlend,
        EmissionBlendMask,
        EmissionBlendMaskScrollRotate,
        EmissionBlendMode,
        EmissionFluorescence,
        UseEmission2nd,
        Emission2ndColor,
        Emission2ndTex,
        Emission2ndTexScrollRotate,
        Emission2ndTexUVMode,
        Emission2ndMainStrength,
        Emission2ndBlend,
        Emission2ndBlendMask,
        Emission2ndBlendMaskScrollRotate,
        Emission2ndBlendMode,
        Emission2ndFluorescence,

        // Normal Map
        UseNormalMap,
        NormalTex,
        NormalTexScale,
        UseNormal2ndMap,
        Normal2ndTex,
        Normal2ndTexUVMode,
        Normal2ndTexScale,
        Normal2ndTexScaleMask,

        // MatCap
        UseMatCap,
        MatCapColor,
        MatCapTex,
        MatCapBlendUV1,
        MatCapZRotCancel,
        MatCapPerspective,
        MatCapVRParallaxStrength,
        MatCapBlend,
        MatCapBlendMask,
        MatCapEnableLighting,
        MatCapBlendMode,
        UseMatCap2nd,
        MatCap2ndColor,
        MatCap2ndTex,
        MatCap2ndBlendUV1,
        MatCap2ndZRotCancel,
        MatCap2ndPerspective,
        MatCap2ndVRParallaxStrength,
        MatCap2ndBlend,
        MatCap2ndBlendMask,
        MatCap2ndEnableLighting,
        MatCap2ndBlendMode,

        // Rim Light
        UseRim,
        RimColor,
        RimColorTex,
        RimBorder,
        RimBlur,
        RimFresnelPower,
        RimEnableLighting,
        RimDirStrength,
        RimDirRange,
        RimIndirRange,
        RimIndirColor,
        RimIndirBorder,
        RimIndirBlur,
        RimBlendMode,

        // Outline
        OutlineColor,
        OutlineTex,
        OutlineTexScrollRotate,
        OutlineWidth,
        OutlineWidthMask,
    }
}